### ISSUE TITLE
CreateTimeRelationship comment/prompt/description parsing consumes too much input

### ISSUE THREAD

**Issue by kevbry** [cmrazek/DkTools#35]
On line 804 of CreateStatement:ParseCreateTimeRelationship:
https://github.com/cmrazek/DkTools/blob/c1869432f1f300609597275eff591fb660d5bc73/DK.Common/Modeling/Tokens/Statements/CreateStatement.cs#L804

I think there's a bug - at least there's a bug when run against our dictionary. The first time relationship in our dict looks like this:
```
create  time relationship dmddmhi 32
        prompt  "Transaction"
        comment "Transactions or changes to the form"
    dmd to dmhi order by effective timeofday ()
```
When "comment" is parsed, the next step is to try to grab the string literal beside it. The existing code uses ExpressionToken.TryParse with a list of stop words. This same code works in the comment parsing for table column defs, since there's a definite stop word of "," at the end in that case, but in this case there's nothing to prevent ExpressionToken.TryParse from consuming both the string literal and the table name on the next line, stopping when it hits "to". This throws the "state machine" of the parser out of whack, and it ends up stuck in ParseCreateTimeRelationship consuming every token until it hits the next relationship or an unexpected token. In my case that manifested as an infinite loop when it runs into an unexpected semicolon later on in the file.

If I replace lines 804 through 805
```
var exp = ExpressionToken.TryParse(Scope, _createTimeRelationshipEndTokens);
if (exp != null) AddToken(exp);
```

with this:
```
if (code.ReadStringLiteral())
{
    AddToken(new StringLiteralToken(Scope, code.Span, code.Text));
}
```

everything works as expected. 

Thanks for making this available

**Comment by cmrazek** [comment]
Thanks @kevbry ,

I added 'stop tokens' so that it stops processing at the end '( )' sequence. This allows the code to continue to work for dictionaries that use stringdefs or macros for prompts/comments rather than hardcoded strings.

This should be fixed in version 1.6.4.0, which is up on the Visual Studio Marketplace now.
